// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function getStories() {
    return invoke<Story[]>("get_stories")
}

export function getSubscriptions() {
    return invoke<Subscription[]>("get_subscriptions")
}

export function addSubscription(url: string) {
    return invoke<null>("add_subscription", { url })
}

export function removeSubscription(name: string) {
    return invoke<null>("remove_subscription", { name })
}

export function refresh() {
    return invoke<null>("refresh")
}

export type Subscription = { name: string; url: string; stories: { [key: string]: Story } }
export type Story = { title: string; link: string; content: string; pubDate: string; starred: boolean; read: boolean }
